using UnityEngine;
using UnityEngine.Events;

namespace _3Plugins.QToolsKit.UIFramework.Scripts.Core
{
    /// <summary>
    /// 此代码由UI编辑器自动生成，请不要修改!
    /// This code is automatically generated by the UI editor, please do not modify!
    /// </summary>
    public abstract class ViewBindBase
    {
        public Transform MTransform { get; set; }
        public abstract void OnInitBind(params UnityAction[] actions);
    }
}