// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DemoUser.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo {

  /// <summary>Holder for reflection information generated from DemoUser.proto</summary>
  public static partial class DemoUserReflection {

    #region Descriptor
    /// <summary>File descriptor for DemoUser.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DemoUserReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5EZW1vVXNlci5wcm90bxIEbWFpbiKlAQoIRGVtb1VzZXISCgoCaWQYASAB",
            "KAUSDAoEbmFtZRgCIAEoCRIOCgZyb2xlSWQYAyABKAkSEgoKcm9sZUFycmF5",
            "cxgEIAMoBRIkCghsb2dpblJlcRgFIAEoCzISLm1haW4uTG9naW5SZXF1ZXN0",
            "EgwKBGlzT2sYBiABKAgSHAoGY29ycHVzGAcgASgOMgwubWFpbi5Db3JwdXMS",
            "CQoBYRgIIAEoAiKKAQoMTG9naW5SZXF1ZXN0Eg8KB2FjY291bnQYASABKAkS",
            "EAoIcGFzc3dvcmQYAiABKAkSKgoEZGljdBgDIAMoCzIcLm1haW4uTG9naW5S",
            "ZXF1ZXN0LkRpY3RFbnRyeRorCglEaWN0RW50cnkSCwoDa2V5GAEgASgFEg0K",
            "BXZhbHVlGAIgASgJOgI4ASpaCgZDb3JwdXMSDQoJVU5JVkVSU0FMEAASBwoD",
            "V0VCEAESCgoGSU1BR0VTEAISCQoFTE9DQUwQAxIICgRORVdTEAQSDAoIUFJP",
            "RFVDVFMQBRIJCgVWSURFTxAGQjRIA6oCL0ltLlVuaXR5LnByb3RvYnVmX3Vu",
            "aXR5LlRlc3RzLlJ1bnRpbWUuUHJvdG9EZW1vYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.DemoUser), global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.DemoUser.Parser, new[]{ "Id", "Name", "RoleId", "RoleArrays", "LoginReq", "IsOk", "Corpus", "A" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.LoginRequest), global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.LoginRequest.Parser, new[]{ "Account", "Password", "Dict" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Enums
  public enum Corpus {
    [pbr::OriginalName("UNIVERSAL")] Universal = 0,
    [pbr::OriginalName("WEB")] Web = 1,
    [pbr::OriginalName("IMAGES")] Images = 2,
    [pbr::OriginalName("LOCAL")] Local = 3,
    [pbr::OriginalName("NEWS")] News = 4,
    [pbr::OriginalName("PRODUCTS")] Products = 5,
    [pbr::OriginalName("VIDEO")] Video = 6,
  }

  #endregion

  #region Messages
  public sealed partial class DemoUser : pb::IMessage<DemoUser>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DemoUser> _parser = new pb::MessageParser<DemoUser>(() => new DemoUser());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DemoUser> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.DemoUserReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DemoUser() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DemoUser(DemoUser other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      roleId_ = other.roleId_;
      roleArrays_ = other.roleArrays_.Clone();
      loginReq_ = other.loginReq_ != null ? other.loginReq_.Clone() : null;
      isOk_ = other.isOk_;
      corpus_ = other.corpus_;
      a_ = other.a_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DemoUser Clone() {
      return new DemoUser(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "roleId" field.</summary>
    public const int RoleIdFieldNumber = 3;
    private string roleId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RoleId {
      get { return roleId_; }
      set {
        roleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "roleArrays" field.</summary>
    public const int RoleArraysFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_roleArrays_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> roleArrays_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> RoleArrays {
      get { return roleArrays_; }
    }

    /// <summary>Field number for the "loginReq" field.</summary>
    public const int LoginReqFieldNumber = 5;
    private global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.LoginRequest loginReq_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.LoginRequest LoginReq {
      get { return loginReq_; }
      set {
        loginReq_ = value;
      }
    }

    /// <summary>Field number for the "isOk" field.</summary>
    public const int IsOkFieldNumber = 6;
    private bool isOk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsOk {
      get { return isOk_; }
      set {
        isOk_ = value;
      }
    }

    /// <summary>Field number for the "corpus" field.</summary>
    public const int CorpusFieldNumber = 7;
    private global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus corpus_ = global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus.Universal;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus Corpus {
      get { return corpus_; }
      set {
        corpus_ = value;
      }
    }

    /// <summary>Field number for the "a" field.</summary>
    public const int AFieldNumber = 8;
    private float a_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float A {
      get { return a_; }
      set {
        a_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DemoUser);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DemoUser other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (RoleId != other.RoleId) return false;
      if(!roleArrays_.Equals(other.roleArrays_)) return false;
      if (!object.Equals(LoginReq, other.LoginReq)) return false;
      if (IsOk != other.IsOk) return false;
      if (Corpus != other.Corpus) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(A, other.A)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (RoleId.Length != 0) hash ^= RoleId.GetHashCode();
      hash ^= roleArrays_.GetHashCode();
      if (loginReq_ != null) hash ^= LoginReq.GetHashCode();
      if (IsOk != false) hash ^= IsOk.GetHashCode();
      if (Corpus != global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus.Universal) hash ^= Corpus.GetHashCode();
      if (A != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(A);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (RoleId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RoleId);
      }
      roleArrays_.WriteTo(output, _repeated_roleArrays_codec);
      if (loginReq_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LoginReq);
      }
      if (IsOk != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsOk);
      }
      if (Corpus != global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus.Universal) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Corpus);
      }
      if (A != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(A);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (RoleId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RoleId);
      }
      roleArrays_.WriteTo(ref output, _repeated_roleArrays_codec);
      if (loginReq_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LoginReq);
      }
      if (IsOk != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsOk);
      }
      if (Corpus != global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus.Universal) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Corpus);
      }
      if (A != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(A);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (RoleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RoleId);
      }
      size += roleArrays_.CalculateSize(_repeated_roleArrays_codec);
      if (loginReq_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LoginReq);
      }
      if (IsOk != false) {
        size += 1 + 1;
      }
      if (Corpus != global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus.Universal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Corpus);
      }
      if (A != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DemoUser other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.RoleId.Length != 0) {
        RoleId = other.RoleId;
      }
      roleArrays_.Add(other.roleArrays_);
      if (other.loginReq_ != null) {
        if (loginReq_ == null) {
          LoginReq = new global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.LoginRequest();
        }
        LoginReq.MergeFrom(other.LoginReq);
      }
      if (other.IsOk != false) {
        IsOk = other.IsOk;
      }
      if (other.Corpus != global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus.Universal) {
        Corpus = other.Corpus;
      }
      if (other.A != 0F) {
        A = other.A;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            RoleId = input.ReadString();
            break;
          }
          case 34:
          case 32: {
            roleArrays_.AddEntriesFrom(input, _repeated_roleArrays_codec);
            break;
          }
          case 42: {
            if (loginReq_ == null) {
              LoginReq = new global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.LoginRequest();
            }
            input.ReadMessage(LoginReq);
            break;
          }
          case 48: {
            IsOk = input.ReadBool();
            break;
          }
          case 56: {
            Corpus = (global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus) input.ReadEnum();
            break;
          }
          case 69: {
            A = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            RoleId = input.ReadString();
            break;
          }
          case 34:
          case 32: {
            roleArrays_.AddEntriesFrom(ref input, _repeated_roleArrays_codec);
            break;
          }
          case 42: {
            if (loginReq_ == null) {
              LoginReq = new global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.LoginRequest();
            }
            input.ReadMessage(LoginReq);
            break;
          }
          case 48: {
            IsOk = input.ReadBool();
            break;
          }
          case 56: {
            Corpus = (global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.Corpus) input.ReadEnum();
            break;
          }
          case 69: {
            A = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LoginRequest : pb::IMessage<LoginRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LoginRequest> _parser = new pb::MessageParser<LoginRequest>(() => new LoginRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Im.Unity.protobuf_unity.Tests.Runtime.ProtoDemo.DemoUserReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginRequest(LoginRequest other) : this() {
      account_ = other.account_;
      password_ = other.password_;
      dict_ = other.dict_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginRequest Clone() {
      return new LoginRequest(this);
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 1;
    private string account_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Account {
      get { return account_; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dict" field.</summary>
    public const int DictFieldNumber = 3;
    private static readonly pbc::MapField<int, string>.Codec _map_dict_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForString(18, ""), 26);
    private readonly pbc::MapField<int, string> dict_ = new pbc::MapField<int, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, string> Dict {
      get { return dict_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Account != other.Account) return false;
      if (Password != other.Password) return false;
      if (!Dict.Equals(other.Dict)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Account.Length != 0) hash ^= Account.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      hash ^= Dict.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Account.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Account);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      dict_.WriteTo(output, _map_dict_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Account.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Account);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      dict_.WriteTo(ref output, _map_dict_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Account.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      size += dict_.CalculateSize(_map_dict_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginRequest other) {
      if (other == null) {
        return;
      }
      if (other.Account.Length != 0) {
        Account = other.Account;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      dict_.Add(other.dict_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Account = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            dict_.AddEntriesFrom(input, _map_dict_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Account = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            dict_.AddEntriesFrom(ref input, _map_dict_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
